# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='rmt_card_ip',
        ),
    ]
